### PR TITLE
Make attachments collapsed by default with a button to show/hide.

### PR DESCRIPTION
**Pull request by beirtipol**
This addresses https://github.com/trivago/cluecumber-report-plugin/issues/227

Tested on a report containing an image and a large Thread Dump text attachment.

### CODE REVIEW

**Comment by beirtipol** [comment]
I needed an 'id' that was compatible with html and thought the hashcode of the 'attachment' object would be most useful in case the user had not set the attachment name/filename etc. so that it could still function.

**Comment by bischoffdev** [comment]
I am currently working on a separate feature. After that I will review your PR.

**Comment by bischoffdev** [comment]
I added the feature. Will be released tomorrow.

**Comment by beirtipol** [comment]
Thanks, I might submit another when I get time. The step detail can
sometimes contain a throwabke with a lot of info. Am thinking to add a
"show more" button if there are more than 10 lines.

**Pull request closed without merging**
