### PR TITLE
Loading Custom Parameters from a file

### PR DESCRIPTION
**Pull request by gazler22**
## Summary

Adding the ability to load custom parameters from a file.

A new parameter named `<customParametersFile>` which takes in the path of a file containing **Key=Value** pairs of parameters has been added to the configuration.

The file can be any properties file with the parameters defined inside. The parameters follow the same format as in the `<customeParameters>` tag.

**Note:**
1. If both the `<customParametersFile>` and `<customeParameters>` tags are defined in the pom, parameters from both of these configuration are added to the report.
2. If two parameters have the same key, the one in the `customParametersFile `will override the one from `customeParameters`

### Unit Tests
Unit test added for `PropertyManager` with a new `.props` file for testing purpose.

### Closing issues
 #166

### Documentation
Documentation as well as the `example-project` have been updated to reflect the new changes.

### CODE REVIEW

**Comment by gazler22** [comment]
> Hi @gazler22 , thanks a lot for your PR. I noticed some minor issues. Is it ok with you if I modify your PR or do you want to do it yourself?

If you can review them it would help me see where I went wrong.

But if its too much work or the issues are minor, go ahead :)

**Comment by laxersaz** [comment]
Hello @gazler22 ,
I am currently rewriting the core Cucable architecture and also reviewing the way some properties are handled. Please bear with me for a little while until I get to your PR. I will try to incorporate this functionality into the new architecture :-)

**Comment by gazler22** [comment]
Ofcourse. Thanks for all your work!

**Comment by gazler22** [comment]
No problem. Thank you :)

**Comment by laxersaz** [comment]
Re-implemented in version 2.0.0

**Pull request closed without merging**
